project:
  type: website
  output-dir: docs

website:
  title: "Li Yuan"
  site-url: "https://liyuan199701.github.io/liyuan.github.io/"
  page-footer:
    center: "© 2026 Li Yuan (Leon) | PhD Candidate in Statistical Science, Southern Methodist University"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: experience.qmd
        text: Experience
      - href: education.qmd
        text: Education
      - href: dating.qmd
        text: Dating
    right:
      - icon: github
        href: https://github.com/LiYuan199701
      - icon: linkedin
        href: https://www.linkedin.com/in/leon-king-436309192/
      - icon: envelope
        href: mailto:yuanli@smu.edu

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full
