<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Li Yuan - Sports Analytics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Privacy-friendly analytics by Plausible -->
<script async="" src="https://plausible.io/js/pa-gqNCaIdhxq-45BBahy_wl.js"></script>
<script>
  window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
  plausible.init()
</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Li Yuan</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./research.html" rel="" target="">
 <span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./publications.html" rel="" target="">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./teaching.html" rel="" target="">
 <span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./experience.html" rel="" target="">
 <span class="menu-text">Experience</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./education.html" rel="" target="">
 <span class="menu-text">Education</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./dating.html" rel="" target="">
 <span class="menu-text">Dating</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./sports.html" rel="" target="" aria-current="page">
 <span class="menu-text">Sports</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/LiYuan199701" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/leon-king-436309192/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:yuanli@smu.edu" rel="" target=""><i class="bi bi-envelope" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sports Analytics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>This page tracks my sports practice data, equipment, and performance analytics over time. The goal is to turn practice into usable feedback: what I shot, what changed, what patterns appeared, and what I should focus on next.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Archery</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Golf</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false">Cycling</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false">Swimming</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-5" role="tab" aria-controls="tabset-2-5" aria-selected="false">Flight Training</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<section id="current-focus" class="level3">
<h3 class="anchored" data-anchor-id="current-focus">Current Focus</h3>
<p>My first tracking area is Olympic recurve archery. I want to record each practice session in a consistent format so I can later analyze score trends, end-by-end consistency, arrow distribution, grouping patterns, and the effects of equipment or technique changes.</p>
</section>
<section id="current-olympic-recurve-setup" class="level3">
<h3 class="anchored" data-anchor-id="current-olympic-recurve-setup">Current Olympic Recurve Setup</h3>
<div class="bow-setup-hero">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/archery-recurve-bow-setup-highlighted.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Highlighted Olympic recurve bow setup with the busy range background removed</figcaption>
</figure>
</div>
</div>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Current setup</th>
<th>Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Riser</td>
<td>Hoyt Formula XD 25” riser</td>
<td>Competition-oriented Olympic recurve platform using the Formula limb system.</td>
</tr>
<tr class="even">
<td>Limbs</td>
<td>Hoyt RCRV Podium Formula Recurve Limbs, long, 28 lb</td>
<td>Long limbs on a 25” riser create an approximately 70” bow with a smoother draw cycle and more forgiving target-shooting feel.</td>
</tr>
<tr class="odd">
<td>Sight</td>
<td>Axcel Achieve XP Pro Sight</td>
<td>Precision sight system for repeatable Olympic recurve aiming and sight-mark tracking.</td>
</tr>
<tr class="even">
<td>Stabilizers</td>
<td>WNS stabilizers</td>
<td>Helps improve aiming steadiness, bow balance, and shot reaction consistency.</td>
</tr>
<tr class="odd">
<td>Clicker</td>
<td>AAE Extended Clicker</td>
<td>Supports consistent draw length, expansion, shot timing, and reduced collapse through the shot.</td>
</tr>
<tr class="even">
<td>Bow stringer</td>
<td>Selway LimbSaver Recurve Stringer, hunter green</td>
<td>Protects the limbs and reduces risk of twist or unsafe stringing.</td>
</tr>
<tr class="odd">
<td>Configuration</td>
<td>Olympic recurve, Formula limb system</td>
<td>Current setup is built for structured target practice and future competition-style training.</td>
</tr>
</tbody>
</table>
</section>
<section id="why-the-28-lb-setup-is-useful" class="level3">
<h3 class="anchored" data-anchor-id="why-the-28-lb-setup-is-useful">Why the 28 lb Setup Is Useful</h3>
<p>The 28 lb limb setup is a good training choice because it prioritizes clean form over raw draw weight. For Olympic recurve, especially while refining alignment, back tension, expansion, clicker control, and shot timing, a smoother and more manageable setup can lead to better long-term scores than struggling with excessive poundage.</p>
<p>This setup should help me:</p>
<ul>
<li>Shoot more arrows per session with less shoulder fatigue.</li>
<li>Build repeatable expansion through the clicker.</li>
<li>Improve holding stability and sight picture quality.</li>
<li>Reduce form breakdown late in practice.</li>
<li>Increase poundage gradually only after technique becomes consistent.</li>
</ul>
</section>
<section id="equipment-and-tuning-watchlist" class="level3">
<h3 class="anchored" data-anchor-id="equipment-and-tuning-watchlist">Equipment and Tuning Watchlist</h3>
<p>These are the next setup variables I should track or confirm as my practice becomes more data-driven:</p>
<ul>
<li>Plunger/button model and setting.</li>
<li>Arrow rest.</li>
<li>Arrow spine, length, point weight, and fletching.</li>
<li>Finger tab and anchor consistency.</li>
<li>Brace height.</li>
<li>Nocking point height.</li>
<li>Tiller and limb alignment.</li>
<li>Stabilizer balance.</li>
<li>Sight marks by distance.</li>
</ul>
</section>
<section id="practice-log" class="level3">
<h3 class="anchored" data-anchor-id="practice-log">Practice Log</h3>
<p>All currently logged archery sessions used a 20-yard distance and a Standard Archery Target 40cm 10 Ring Bow and Arrow Target.</p>
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Date</th>
<th style="text-align: right;">Time</th>
<th>Session</th>
<th style="text-align: right;">Distance</th>
<th>Target / app label</th>
<th style="text-align: right;">Ends</th>
<th style="text-align: right;">Arrows</th>
<th style="text-align: right;">Reported score</th>
<th style="text-align: right;">Standard 10-ring score</th>
<th style="text-align: right;">Avg / Arrow</th>
<th style="text-align: right;">X</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2026-05-23</td>
<td style="text-align: right;">3:36 PM</td>
<td>Scorecard app screenshot</td>
<td style="text-align: right;">20 yd</td>
<td>40cm 10-ring target</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">283</td>
<td style="text-align: right;">283 / 360 (78.6%)</td>
<td style="text-align: right;">7.86</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>2026-05-23</td>
<td style="text-align: right;">4:29 PM</td>
<td>Custom-(Lancaster): Preston Leon</td>
<td style="text-align: right;">20 yd</td>
<td>40cm LAS Indoor</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">237</td>
<td style="text-align: right;">236 / 300 (78.7%)</td>
<td style="text-align: right;">7.87</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td>2026-05-23</td>
<td style="text-align: right;">5:23 PM</td>
<td>Custom-(WA, Metric): Preston Leon 2</td>
<td style="text-align: right;">20 yd</td>
<td>40cm WA Target</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">70 / 90 (77.8%)</td>
<td style="text-align: right;">7.78</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><a href="data/archery_practice_log.csv" class="btn btn-primary">Download archery practice CSV</a> <a href="files/sports/archery-2026-05-23-1629-scorecard-preston-leon.pdf" class="btn btn-secondary">View 4:29 PM scorecard PDF</a> <a href="files/sports/archery-2026-05-23-1723-scorecard-preston-leon-2.pdf" class="btn btn-secondary">View 5:23 PM scorecard PDF</a></p>
</section>
<section id="sight-setup-log" class="level3">
<h3 class="anchored" data-anchor-id="sight-setup-log">Sight Setup Log</h3>
<p>The sight setting below was used for the May 23, 2026 practice data at 20 yards. Because the close-up photos preserve the sight geometry better than the small printed dial marks, I am treating the images as the official setup record and only recording numeric values when they can be read clearly.</p>
<div class="sight-setup-note">
<p><strong>May 23, 2026 sight mark:</strong> Axcel Achieve XP Pro Sight, 20 yards, Standard Archery Target 40cm 10 Ring Bow and Arrow Target. From the closer photos, the side reference scale reads approximately <code>5.5</code> visible tick marks, the windage dial appears between <code>7</code> and <code>8</code> and closest to about <code>7.8</code>, and the blue sight-head reference marks appear near the center index. These are photo-based readings, so I should confirm the exact manufacturer units/click values at the range.</p>
</div>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>May 23 setup record</th>
<th>Confidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Distance</td>
<td>20 yards</td>
<td>Confirmed</td>
</tr>
<tr class="even">
<td>Target face</td>
<td>Standard Archery Target 40cm 10 Ring Bow and Arrow Target</td>
<td>Confirmed</td>
</tr>
<tr class="odd">
<td>Sight</td>
<td>Axcel Achieve XP Pro Sight</td>
<td>Confirmed from setup</td>
</tr>
<tr class="even">
<td>Side reference scale</td>
<td>Approximately <code>5.5</code> visible tick marks on the close side scale</td>
<td>Approximate from close-up</td>
</tr>
<tr class="odd">
<td>Windage dial</td>
<td>Between <code>7</code> and <code>8</code>, closest to about <code>7.8</code> on the visible gray dial</td>
<td>Approximate from close-up</td>
</tr>
<tr class="even">
<td>Windage center index</td>
<td>Blue sight-head reference marks appear close to the center / long middle mark</td>
<td>Photo reference</td>
</tr>
<tr class="odd">
<td>Elevation</td>
<td>Main vertical elevation bar number is not visible in these close-ups; keep the photo set as the current reference and confirm the exact elevation mark next session</td>
<td>Needs range confirmation</td>
</tr>
<tr class="even">
<td>Aperture position</td>
<td>Aperture mounted on the threaded rod to the archer’s right of the blue sight block</td>
<td>Photo reference</td>
</tr>
</tbody>
</table>
<p><a href="data/archery_sight_settings.csv" class="btn btn-primary">Download archery sight settings CSV</a></p>
<div class="sight-setup-grid">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/archery-2026-05-23-sight-close-windage-dial.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Close-up windage dial reference for the May 23 sight setup</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/archery-2026-05-23-sight-close-side-scale.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Close-up side scale reference showing approximately 5.5 visible tick marks</figcaption>
</figure>
</div>
</div>
</section>
<section id="scorecard-style-breakdowns" class="level3">
<h3 class="anchored" data-anchor-id="scorecard-style-breakdowns">2026-05-23 Scorecard-Style Breakdowns</h3>
<p>The tables below follow the PDF scorecard structure: each row is one end, each arrow score is shown separately, <code>Total</code> is the end total, and <code>Score</code> is the cumulative running score.</p>
<div class="score-legend">
<p><strong>Score color key:</strong> <span class="score-badge score-yellow">X/10/9</span> <span class="score-badge score-red">8/7</span> <span class="score-badge score-blue">6/5</span> <span class="score-badge score-black">4/3</span> <span class="score-badge score-white">2/1</span></p>
</div>
<section id="pm-scorecard-app-screenshot" class="level4">
<h4 class="anchored" data-anchor-id="pm-scorecard-app-screenshot">3:36 PM Scorecard App Screenshot</h4>
<div class="archery-scorecard-wrap">

<table class="archery-scorecard">
<thead>
<tr class="scorecard-title">
<th colspan="10">
Distance #1: 20yd (40cm 10 Ring Target)
</th>
</tr>
<tr>
<th>
End
</th>
<th>
1
</th>
<th>
2
</th>
<th>
3
</th>
<th>
4
</th>
<th>
5
</th>
<th>
6
</th>
<th>
Avg.
</th>
<th>
Total
</th>
<th>
Score
</th>
</tr>
</thead>
<tbody>
<tr>
<th>
1
</th>
<td class="score-yellow">
9
</td>
<td class="score-yellow">
9
</td>
<td class="score-yellow">
9
</td>
<td class="score-red">
8
</td>
<td class="score-red">
8
</td>
<td class="score-blue">
6
</td>
<td>
8.17
</td>
<td>
49
</td>
<td>
49
</td>
</tr>
<tr>
<th>
2
</th>
<td class="score-yellow">
9
</td>
<td class="score-yellow">
9
</td>
<td class="score-red">
8
</td>
<td class="score-red">
8
</td>
<td class="score-blue">
6
</td>
<td class="score-white">
2
</td>
<td>
7
</td>
<td>
42
</td>
<td>
91
</td>
</tr>
<tr>
<th>
3
</th>
<td class="score-yellow">
9
</td>
<td class="score-yellow">
10
</td>
<td class="score-yellow">
9
</td>
<td class="score-yellow">
9
</td>
<td class="score-blue">
5
</td>
<td class="score-yellow">
9
</td>
<td>
8.5
</td>
<td>
51
</td>
<td>
142
</td>
</tr>
<tr>
<th>
4
</th>
<td class="score-yellow">
9
</td>
<td class="score-yellow">
10
</td>
<td class="score-yellow">
9
</td>
<td class="score-red">
7
</td>
<td class="score-red">
7
</td>
<td class="score-blue">
6
</td>
<td>
8
</td>
<td>
48
</td>
<td>
190
</td>
</tr>
<tr>
<th>
5
</th>
<td class="score-yellow">
9
</td>
<td class="score-yellow">
9
</td>
<td class="score-red">
8
</td>
<td class="score-red">
7
</td>
<td class="score-red">
8
</td>
<td class="score-blue">
6
</td>
<td>
7.83
</td>
<td>
47
</td>
<td>
237
</td>
</tr>
<tr>
<th>
6
</th>
<td class="score-yellow">
9
</td>
<td class="score-yellow">
9
</td>
<td class="score-red">
7
</td>
<td class="score-red">
8
</td>
<td class="score-red">
7
</td>
<td class="score-blue">
6
</td>
<td>
7.67
</td>
<td>
46
</td>
<td>
283
</td>
</tr>
</tbody>

</table>
</div>
</section>
<section id="pm-custom-lancaster-preston-leon" class="level4">
<h4 class="anchored" data-anchor-id="pm-custom-lancaster-preston-leon">4:29 PM Custom-(Lancaster): Preston Leon</h4>
<p>This table follows the attached Lancaster PDF format. The official scorecard reports 237 because this Lancaster-style scorecard counts <code>X</code> as 11. For standard 10-ring comparison, the equivalent is 236 / 300.</p>
<div class="archery-scorecard-wrap">

<table class="archery-scorecard">
<thead>
<tr class="scorecard-title">
<th colspan="7">
Distance #1: 20yd (40cm LAS Indoor)
</th>
</tr>
<tr>
<th>
End
</th>
<th>
1
</th>
<th>
2
</th>
<th>
3
</th>
<th>
Avg.
</th>
<th>
Total
</th>
<th>
Score
</th>
</tr>
</thead>
<tbody>
<tr>
<th>
1
</th>
<td class="score-red">
8
</td>
<td class="score-blue">
6
</td>
<td class="score-red">
7
</td>
<td>
7
</td>
<td>
21
</td>
<td>
21
</td>
</tr>
<tr>
<th>
2
</th>
<td class="score-blue">
6
</td>
<td class="score-blue">
6
</td>
<td class="score-blue">
6
</td>
<td>
6
</td>
<td>
18
</td>
<td>
39
</td>
</tr>
<tr>
<th>
3
</th>
<td class="score-yellow">
9
</td>
<td class="score-yellow">
9
</td>
<td class="score-yellow">
9
</td>
<td>
9
</td>
<td>
27
</td>
<td>
66
</td>
</tr>
<tr>
<th>
4
</th>
<td class="score-blue">
6
</td>
<td class="score-red">
7
</td>
<td class="score-blue">
6
</td>
<td>
6.33
</td>
<td>
19
</td>
<td>
85
</td>
</tr>
<tr>
<th>
5
</th>
<td class="score-yellow">
9
</td>
<td class="score-red">
8
</td>
<td class="score-red">
8
</td>
<td>
8.33
</td>
<td>
25
</td>
<td>
110
</td>
</tr>
<tr>
<th>
6
</th>
<td class="score-yellow">
10
</td>
<td class="score-red">
8
</td>
<td class="score-yellow">
9
</td>
<td>
9
</td>
<td>
27
</td>
<td>
137
</td>
</tr>
<tr>
<th>
7
</th>
<td class="score-yellow">
9
</td>
<td class="score-red">
8
</td>
<td class="score-red">
7
</td>
<td>
8
</td>
<td>
24
</td>
<td>
161
</td>
</tr>
<tr>
<th>
8
</th>
<td class="score-yellow">
9
</td>
<td class="score-yellow">
9
</td>
<td class="score-red">
7
</td>
<td>
8.33
</td>
<td>
25
</td>
<td>
186
</td>
</tr>
<tr>
<th>
9
</th>
<td class="score-red">
8
</td>
<td class="score-red">
8
</td>
<td class="score-red">
8
</td>
<td>
8
</td>
<td>
24
</td>
<td>
210
</td>
</tr>
<tr>
<th>
10
</th>
<td class="score-yellow">
X
</td>
<td class="score-red">
8
</td>
<td class="score-red">
8
</td>
<td>
9
</td>
<td>
27
</td>
<td>
237
</td>
</tr>
</tbody>

</table>
</div>
<div class="archery-scorecard-wrap">

<table class="archery-scorecard archery-summary-table">
<thead>
<tr class="scorecard-title">
<th colspan="8">
Distance #1 Totals - Skill: 59.7
</th>
</tr>
<tr>
<th>
Xs
</th>
<th>
10s
</th>
<th>
9s
</th>
<th>
Arrow Avg.
</th>
<th>
Avg. End
</th>
<th>
Score
</th>
<th>
Gold
</th>
<th>
Xs+10s
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
1
</td>
<td>
1
</td>
<td>
8
</td>
<td>
7.9
</td>
<td>
23.7
</td>
<td>
237
</td>
<td>
33.33%
</td>
<td>
2
</td>
</tr>
</tbody>

</table>
</div>
</section>
<section id="pm-custom-wa-metric-preston-leon-2" class="level4">
<h4 class="anchored" data-anchor-id="pm-custom-wa-metric-preston-leon-2">5:23 PM Custom-(WA, Metric): Preston Leon 2</h4>
<div class="archery-scorecard-wrap">

<table class="archery-scorecard">
<thead>
<tr class="scorecard-title">
<th colspan="7">
Distance #1: 20yd (40cm WA Target)
</th>
</tr>
<tr>
<th>
End
</th>
<th>
1
</th>
<th>
2
</th>
<th>
3
</th>
<th>
Avg.
</th>
<th>
Total
</th>
<th>
Score
</th>
</tr>
</thead>
<tbody>
<tr>
<th>
1
</th>
<td class="score-yellow">
9
</td>
<td class="score-red">
7
</td>
<td class="score-red">
7
</td>
<td>
7.67
</td>
<td>
23
</td>
<td>
23
</td>
</tr>
<tr>
<th>
2
</th>
<td class="score-yellow">
9
</td>
<td class="score-red">
8
</td>
<td class="score-red">
7
</td>
<td>
8
</td>
<td>
24
</td>
<td>
47
</td>
</tr>
<tr>
<th>
3
</th>
<td class="score-yellow">
9
</td>
<td class="score-red">
7
</td>
<td class="score-red">
7
</td>
<td>
7.67
</td>
<td>
23
</td>
<td>
70
</td>
</tr>
</tbody>

</table>
</div>
<div class="archery-scorecard-wrap">

<table class="archery-scorecard archery-summary-table">
<thead>
<tr class="scorecard-title">
<th colspan="8">
Distance #1 Totals - Skill: 56.9
</th>
</tr>
<tr>
<th>
Xs
</th>
<th>
10s
</th>
<th>
9s
</th>
<th>
Arrow Avg.
</th>
<th>
Avg. End
</th>
<th>
Score
</th>
<th>
Gold
</th>
<th>
Xs+10s
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
0
</td>
<td>
0
</td>
<td>
3
</td>
<td>
7.78
</td>
<td>
23.33
</td>
<td>
70
</td>
<td>
33.33%
</td>
<td>
0
</td>
</tr>
</tbody>

</table>
</div>
</section>
</section>
<section id="shooting-distribution-pattern" class="level3">
<h3 class="anchored" data-anchor-id="shooting-distribution-pattern">Shooting Distribution Pattern</h3>
<div class="sports-image-grid">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/archery-2026-05-23-1629-scorecard-target.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">4:29 PM ArcherySuccess target distribution pattern</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/archery-2026-05-23-1723-scorecard-target.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">5:23 PM ArcherySuccess target distribution pattern</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/archery-2026-05-23-target-overview.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">3:36 PM scorecard app target overview</figcaption>
</figure>
</div>
</div>
</section>
<section id="may-23-cumulative-analytics" class="level3">
<h3 class="anchored" data-anchor-id="may-23-cumulative-analytics">May 23 Cumulative Analytics</h3>
<div class="sports-metric-grid">
<div class="sports-metric-card">
<p><strong>Standard score</strong></p>
<p>589 / 750</p>
</div>
<div class="sports-metric-card">
<p><strong>Average arrow</strong></p>
<p>7.85</p>
</div>
<div class="sports-metric-card">
<p><strong>Total arrows</strong></p>
<p>75</p>
</div>
<div class="sports-metric-card">
<p><strong>Gold-ring arrows</strong></p>
<p>30 / 75</p>
</div>
</div>
<p>Standard 10-ring score distribution across the May 23 data:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Score value</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Share of arrows</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">X</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.3%</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.0%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">34.7%</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">24.0%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">18.7%</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">14.7%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.3%</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.3%</td>
</tr>
</tbody>
</table>
<p>Early read:</p>
<ul>
<li>Across 75 logged arrows at 20 yards, the standard 10-ring equivalent score is 589/750, or 78.5%.</li>
<li>The three sessions were consistent by percentage: 78.6%, 78.7%, and 77.8%.</li>
<li>Gold-ring scoring is the current strength: 30 of 75 arrows were X, 10, or 9.</li>
<li>The main opportunity is reducing low outliers: 13 of 75 arrows were 6 or lower, including one 2 from the first scorecard screenshot.</li>
<li>The 4:29 PM scorecard had no misses and a strong official skill rating of 59.7, but it also showed several 6s, so the next quality jump should come from lifting the floor rather than chasing only more 10s.</li>
<li>The target plots suggest a mild left-side grouping tendency plus occasional low-right outliers; I should confirm this across multiple sessions before changing tuning.</li>
</ul>
</section>
<section id="future-data-fields" class="level3">
<h3 class="anchored" data-anchor-id="future-data-fields">Future Data Fields</h3>
<p>For each future archery practice, I should record:</p>
<ul>
<li>Date, time, location, distance, target face, indoor/outdoor conditions.</li>
<li>Bow setup, limb weight, arrows, plunger setting, brace height, and sight mark.</li>
<li>Sight photos or exact sight numbers: horizontal extension, elevation, windage, aperture/pin position, and any click changes.</li>
<li>End-by-end score and raw arrow scores.</li>
<li>X count, 10 count, 9+ count, and low-arrow count.</li>
<li>Notes about form, clicker behavior, aiming stability, fatigue, and mental focus.</li>
<li>A target screenshot or photo when available.</li>
</ul>
</section>
<section id="next-practice-goal" class="level3">
<h3 class="anchored" data-anchor-id="next-practice-goal">Next Practice Goal</h3>
<p>For the next several sessions, the priority is not only increasing the total score. The first goal is reducing the low outlier arrows while preserving the number of 9s and 10s. A practical target is to keep all arrows at 6 or higher, then push toward all arrows at 7 or higher.</p>
</section>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<section id="may-22-2026-simulator-practice" class="level3">
<h3 class="anchored" data-anchor-id="may-22-2026-simulator-practice">May 22, 2026 Simulator Practice</h3>
<p>This session records my driver practice at <a href="https://www.royalgolfzone.com/">Royal Golf Zone</a> on Friday, May 22, 2026 at 6:00 PM. The screenshots contain 30 unique visible driver shots. I use two views of the data:</p>
<ul>
<li><strong>Raw visible shots:</strong> all 30 transcribed shots from the screenshots.</li>
<li><strong>Full-contact subset:</strong> 23 shots with carry at least 150 yards and ball speed at least 100 mph, so obvious mishits or simulator misreads do not dominate the analytics.</li>
</ul>
<p><a href="data/golf_simulator_driver_visible_shots.csv" class="btn btn-primary">Download visible driver shot CSV</a></p>
<table class="table">
<thead>
<tr class="header">
<th>Field</th>
<th>Session record</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Date and time</td>
<td>2026-05-22, 6:00 PM</td>
</tr>
<tr class="even">
<td>Venue</td>
<td><a href="https://www.royalgolfzone.com/">Royal Golf Zone</a></td>
</tr>
<tr class="odd">
<td>Practice type</td>
<td>Indoor golf simulator</td>
</tr>
<tr class="even">
<td>Club</td>
<td>Driver</td>
</tr>
<tr class="odd">
<td>Visible shots recorded</td>
<td>30</td>
</tr>
<tr class="even">
<td>Full-contact shots analyzed</td>
<td>23</td>
</tr>
<tr class="odd">
<td>Units</td>
<td>mph, rpm, yards, degrees</td>
</tr>
</tbody>
</table>
</section>
<section id="driver-snapshot" class="level3">
<h3 class="anchored" data-anchor-id="driver-snapshot">Driver Snapshot</h3>
<div class="sports-metric-grid">
<div class="sports-metric-card">
<p><strong>Best total distance</strong></p>
<p>230 yd</p>
</div>
<div class="sports-metric-card">
<p><strong>Best carry</strong></p>
<p>217 yd</p>
</div>
<div class="sports-metric-card">
<p><strong>Avg. full-contact distance</strong></p>
<p>206.2 yd</p>
</div>
<div class="sports-metric-card">
<p><strong>Avg. full-contact carry</strong></p>
<p>192.2 yd</p>
</div>
<div class="sports-metric-card">
<p><strong>Avg. full-contact ball speed</strong></p>
<p>122.0 mph</p>
</div>
<div class="sports-metric-card">
<p><strong>Avg. full-contact club speed</strong></p>
<p>86.3 mph</p>
</div>
<div class="sports-metric-card">
<p><strong>200+ yd total distance</strong></p>
<p>17 / 23</p>
</div>
<div class="sports-metric-card">
<p><strong>210+ yd total distance</strong></p>
<p>10 / 23</p>
</div>
</div>
</section>
<section id="top-recorded-driver-shots" class="level3">
<h3 class="anchored" data-anchor-id="top-recorded-driver-shots">Top Recorded Driver Shots</h3>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Shot</th>
<th style="text-align: right;">Ball speed</th>
<th style="text-align: right;">Club speed</th>
<th style="text-align: right;">Carry</th>
<th style="text-align: right;">Distance</th>
<th style="text-align: right;">Side angle</th>
<th style="text-align: right;">Launch / height</th>
<th style="text-align: right;">Club path</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">31</td>
<td style="text-align: right;">133.2 mph</td>
<td style="text-align: right;">94.2 mph</td>
<td style="text-align: right;">217 yd</td>
<td style="text-align: right;">230 yd</td>
<td style="text-align: right;">-4.9 deg</td>
<td style="text-align: right;">13.4 deg</td>
<td style="text-align: right;">-6.9 deg</td>
<td>Best visible carry and total distance</td>
</tr>
<tr class="even">
<td style="text-align: right;">38</td>
<td style="text-align: right;">129.6 mph</td>
<td style="text-align: right;">91.7 mph</td>
<td style="text-align: right;">213 yd</td>
<td style="text-align: right;">226 yd</td>
<td style="text-align: right;">-2.4 deg</td>
<td style="text-align: right;">15.0 deg</td>
<td style="text-align: right;">-2.1 deg</td>
<td>Strong long drive</td>
</tr>
<tr class="odd">
<td style="text-align: right;">39</td>
<td style="text-align: right;">126.9 mph</td>
<td style="text-align: right;">89.7 mph</td>
<td style="text-align: right;">210 yd</td>
<td style="text-align: right;">222 yd</td>
<td style="text-align: right;">-0.1 deg</td>
<td style="text-align: right;">17.0 deg</td>
<td style="text-align: right;">0.0 deg</td>
<td>Best start-line control among long shots</td>
</tr>
<tr class="even">
<td style="text-align: right;">49</td>
<td style="text-align: right;">126.0 mph</td>
<td style="text-align: right;">89.1 mph</td>
<td style="text-align: right;">205 yd</td>
<td style="text-align: right;">218 yd</td>
<td style="text-align: right;">-3.9 deg</td>
<td style="text-align: right;">14.5 deg</td>
<td style="text-align: right;">0.0 deg</td>
<td>Solid carry and direction</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">127.2 mph</td>
<td style="text-align: right;">90.0 mph</td>
<td style="text-align: right;">204 yd</td>
<td style="text-align: right;">217 yd</td>
<td style="text-align: right;">-6.0 deg</td>
<td style="text-align: right;">12.5 deg</td>
<td style="text-align: right;">-12.1 deg</td>
<td>Good speed with left-side tendency</td>
</tr>
<tr class="even">
<td style="text-align: right;">26</td>
<td style="text-align: right;">128.2 mph</td>
<td style="text-align: right;">90.6 mph</td>
<td style="text-align: right;">204 yd</td>
<td style="text-align: right;">216 yd</td>
<td style="text-align: right;">-6.0 deg</td>
<td style="text-align: right;">12.8 deg</td>
<td style="text-align: right;">-19.1 deg</td>
<td>Strong speed, path needs cleanup</td>
</tr>
<tr class="odd">
<td style="text-align: right;">55</td>
<td style="text-align: right;">126.2 mph</td>
<td style="text-align: right;">89.2 mph</td>
<td style="text-align: right;">201 yd</td>
<td style="text-align: right;">215 yd</td>
<td style="text-align: right;">-9.8 deg</td>
<td style="text-align: right;">12.3 deg</td>
<td style="text-align: right;">-2.7 deg</td>
<td>Good power, left start</td>
</tr>
<tr class="even">
<td style="text-align: right;">62</td>
<td style="text-align: right;">122.2 mph</td>
<td style="text-align: right;">86.4 mph</td>
<td style="text-align: right;">202 yd</td>
<td style="text-align: right;">215 yd</td>
<td style="text-align: right;">2.1 deg</td>
<td style="text-align: right;">19.3 deg</td>
<td style="text-align: right;">0.0 deg</td>
<td>High launch with straight path reading</td>
</tr>
</tbody>
</table>
</section>
<section id="performance-read" class="level3">
<h3 class="anchored" data-anchor-id="performance-read">Performance Read</h3>
<ul>
<li>My current driver ceiling is encouraging: the best visible shot reached 230 yards total distance and 217 yards carry, with 133.2 mph ball speed and 94.2 mph club speed.</li>
<li>The full-contact average was 206.2 yards total distance and 192.2 yards carry, which is a useful baseline for future simulator sessions.</li>
<li>Contact consistency is the biggest near-term opportunity. Seven visible shots were excluded from the clean subset because they were obvious mishits, weak contacts, or simulator misreads.</li>
<li>Direction control trends slightly left on the clean shots: 15 of 23 full-contact shots had negative side angle, and the average side angle was -2.2 degrees.</li>
<li>Several strong shots also showed large negative club-path readings, especially shots 52, 48, 50, 23, and 26. The next practice goal should be narrowing club path and start line before chasing more raw speed.</li>
<li>Launch/height on full-contact shots averaged 14.2 degrees, with average backspin around 2,740 rpm. That is a usable driver window, but reducing side-spin volatility should improve dispersion.</li>
</ul>
</section>
<section id="next-golf-practice-goals" class="level3">
<h3 class="anchored" data-anchor-id="next-golf-practice-goals">Next Golf Practice Goals</h3>
<ul>
<li>Keep at least 80% of driver shots above 150 yards carry.</li>
<li>Keep full-contact side angle inside +/-5 degrees.</li>
<li>Keep club path inside +/-5 degrees on more swings.</li>
<li>Track whether misses are mostly left-starting, slicing/fading, or contact-related.</li>
<li>Record the same metrics by club once I begin practicing irons, wedges, and putting.</li>
</ul>
</section>
<section id="impact-and-ball-flight-fundamentals" class="level3">
<h3 class="anchored" data-anchor-id="impact-and-ball-flight-fundamentals">Impact and Ball Flight Fundamentals</h3>
<p>These notes are my working reference for understanding launch-monitor data. I want to connect every simulator number to one of two questions: <strong>Did I create enough energy?</strong> and <strong>Did I deliver the club in a way that sent the ball where I intended?</strong></p>
<div class="golf-fundamentals-note">
<p><strong>Core model:</strong> distance comes first from ball speed, then gets shaped by launch angle, spin rate, descent angle, and ground conditions. Direction starts mostly from where the face is pointed at impact, while curve comes from the face-to-path relationship, centeredness of strike, spin axis, and gear effect.</p>
</div>
<div class="golf-fundamentals-grid">
<div class="golf-fundamental-card">
<p><strong>1. Distance</strong><br>
<strong>MAXIMIZING DISTANCE</strong></p>
<p>Distance is not just swing speed. It is the final result of ball speed, smash factor, launch angle, spin rate, carry, descent angle, and bounce/roll. For driver practice, I should first raise the floor: more solid contacts above 150 yd carry, then push ball speed and optimize launch/spin.</p>
</div>
<div class="golf-fundamental-card">
<p><strong>2. Smash Factor</strong><br>
<strong>SMASH FACTOR FUNDAMENTAL</strong></p>
<p>Smash factor is <code>ball speed / club speed</code>. It measures energy transfer at impact. My May 22 clean-driver average was about <code>122.0 / 86.3 = 1.41</code>, while my GolfTech best shots reached <code>1.47</code> and <code>1.50</code>. A low smash number usually points to off-center contact, poor face control, or too much spin loft.</p>
</div>
<div class="golf-fundamental-card">
<p><strong>3. Spin Rate</strong><br>
<strong>SPIN RATE FUNDAMENTAL</strong></p>
<p>Spin rate is the total backspin that helps the ball stay in the air but can also cost distance if it is too high. My Royal Golf Zone full-contact average was about <code>2,740 rpm</code>, while one GolfTech best shot showed <code>3,661 rpm</code>, which likely explains why that 207 yd shot had good speed but a lower, spinny flight.</p>
</div>
<div class="golf-fundamental-card">
<p><strong>4. Launch Angle</strong><br>
<strong>LAUNCH ANGLE FUNDAMENTAL</strong></p>
<p>Launch angle is the vertical angle the ball leaves the clubface. My Royal Golf Zone clean-driver average was about <code>14.2 deg</code>, which is a useful window. The GolfTech 207 yd shot launched at <code>9 deg</code>, probably too low for maximizing carry; the 206 yd shot launched at <code>16 deg</code>, which produced better carry but still needs dispersion control.</p>
</div>
<div class="golf-fundamental-card">
<p><strong>5. Launch Direction</strong><br>
<strong>LAUNCH DIRECTION FUNDAMENTAL</strong></p>
<p>Launch direction is the horizontal start line. For my data, the side angle is the practical proxy: negative values started left, positive values started right. My full-contact average side angle was about <code>-2.2 deg</code>, so my current driver pattern trends slightly left. A useful near-term goal is keeping start line inside <code>+/-5 deg</code>.</p>
</div>
<div class="golf-fundamental-card">
<p><strong>6. Club Path</strong><br>
<strong>SWING DIRECTION - CALCULATOR</strong></p>
<p>Club path is where the clubhead is moving horizontally through impact. Negative values in my simulator data suggest out-to-in / leftward delivery. A rough swing-direction checkpoint is: if launch direction and club path are both left, I need to check alignment and path; if launch starts left but curves right, face-to-path is probably open.</p>
</div>
<div class="golf-fundamental-card">
<p><strong>7. Spin Axis 1</strong><br>
<strong>SPIN AXIS 1 CALCULATOR</strong></p>
<p>A useful approximation is <code>spin-axis proxy = atan(side spin / backspin)</code>. Example: shot 52 had <code>1389 rpm</code> side spin and <code>2816 rpm</code> backspin, which gives about <code>26 deg</code> of axis tilt - a big curve signal. Shot 62 had <code>0</code> side spin, so the proxy is near <code>0 deg</code>.</p>
</div>
<div class="golf-fundamental-card">
<p><strong>8. Spin Axis 2</strong><br>
<strong>GEAR EFFECT</strong></p>
<p>Gear effect comes from off-center driver impact. Toe strikes can tilt spin toward draw/hook; heel strikes can tilt spin toward fade/slice. This means a shot can show a surprising spin axis even when path and face look reasonable. Next step: use foot spray or impact tape to connect strike location to curvature.</p>
</div>
<div class="golf-fundamental-card">
<p><strong>9. Straight Shot</strong><br>
<strong>STRAIGHT SHOT W/ DUFNER</strong></p>
<p>For a straight-shot baseline, I want three things at once: centered strike, face near target, and face-to-path near zero. The “Dufner” checkpoint for me is boring on purpose: balanced finish, stable face, neutral path, and a start line that does not require rescue curve.</p>
</div>
<div class="golf-fundamental-card">
<p><strong>10. Bounce &amp; Roll</strong><br>
<strong>BOUNCE &amp; ROLL - CALCULATOR</strong></p>
<p>Total distance equals carry plus rollout. Rollout depends on landing angle, spin, ball speed, turf firmness, and slope. In simulator practice, I should track both carry and total distance because a long total can hide a low-launch shot that would be less reliable outdoors.</p>
</div>
</div>
<section id="practice-calculators-and-checkpoints" class="level4">
<h4 class="anchored" data-anchor-id="practice-calculators-and-checkpoints">Practice Calculators and Checkpoints</h4>
<div class="golf-table-wrap">
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Topic</th>
<th>Quick formula or checkpoint</th>
<th>What I should watch in my data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Distance</td>
<td><code>Total = carry + bounce/roll</code></td>
<td>Do not chase total distance only; carry is the more transferable baseline.</td>
</tr>
<tr class="even">
<td>Smash factor</td>
<td><code>Ball speed / club speed</code></td>
<td>Current clean-driver average is about <code>1.41</code>; best GolfTech smash reached <code>1.50</code>.</td>
</tr>
<tr class="odd">
<td>Spin rate</td>
<td>Backspin in rpm</td>
<td>Royal clean average is about <code>2,740 rpm</code>; GolfTech 3,661 rpm shot likely spun too much.</td>
</tr>
<tr class="even">
<td>Launch angle</td>
<td>Vertical launch in degrees</td>
<td>Keep driver launch in a usable window; compare 9 deg low launch vs 16 deg better carry.</td>
</tr>
<tr class="odd">
<td>Launch direction</td>
<td>Horizontal start line / side angle</td>
<td>Current pattern trends left; target should be inside <code>+/-5 deg</code>.</td>
</tr>
<tr class="even">
<td>Club path</td>
<td>Horizontal clubhead direction at impact</td>
<td>Several strong shots had negative path; reduce extreme leftward delivery.</td>
</tr>
<tr class="odd">
<td>Face-to-path</td>
<td><code>Face angle - club path</code> when face data is available</td>
<td>This is the main curve diagnosis; near zero is the straight-shot baseline.</td>
</tr>
<tr class="even">
<td>Spin-axis proxy</td>
<td><code>atan(side spin / backspin)</code></td>
<td>Shot 52 proxy is about 26 deg, showing why side spin matters.</td>
</tr>
<tr class="odd">
<td>Gear effect</td>
<td>Compare strike location with curve</td>
<td>Add impact spray/tape to explain toe/heel misses.</td>
</tr>
<tr class="even">
<td>Rollout</td>
<td><code>Total distance - carry distance</code></td>
<td>Track whether distance is coming from reliable carry or risky low-launch roll.</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="how-this-connects-to-my-current-driver-work" class="level4">
<h4 class="anchored" data-anchor-id="how-this-connects-to-my-current-driver-work">How This Connects to My Current Driver Work</h4>
<ul>
<li><strong>Distance:</strong> My best visible Royal Golf Zone total was 230 yd, but the stronger long-term KPI is raising average carry from about 192 yd while reducing mishits.</li>
<li><strong>Energy transfer:</strong> My GolfTech best smash factor of 1.50 shows I can create efficient driver impact; the next step is making that contact repeatable.</li>
<li><strong>Launch and spin:</strong> The 207 yd GolfTech shot had strong speed but low launch and high spin. The 206 yd shot had better carry and smash, but dispersion was wider.</li>
<li><strong>Direction:</strong> The Royal clean-shot set leaned left by side angle. Before chasing speed, I should make start line and path tighter.</li>
<li><strong>Curvature:</strong> Side spin and spin-axis proxy show why path alone is not enough. Impact location and gear effect may explain some big misses.</li>
</ul>
<p>Sources and useful references: <a href="https://www.trackman.com/de/blog/golf/face-to-path">TrackMan on face-to-path</a>, <a href="https://www.titleist.ca/learning-lab/performance/golf-club-path">Titleist Learning Lab on club path and launch direction</a>, <a href="https://www.trackman.com/blog/golf/trackman-talks-master-the-smash-index-and-spin-index">TrackMan on smash/spin concepts</a>, and <a href="https://www.skytrakgolf.com/blogs/articles/understanding-golf-ball-data-what-every-metric-actually-means-for-your-game">SkyTrak on launch-monitor ball data</a>.</p>
</section>
</section>
<section id="golf-ball-science-golftech-best-shots-and-bag-fitting" class="level3">
<h3 class="anchored" data-anchor-id="golf-ball-science-golftech-best-shots-and-bag-fitting">Golf Ball Science, GolfTech Best Shots, and Bag Fitting</h3>
<section id="why-golf-balls-are-this-size-and-why-they-have-dimples" class="level4">
<h4 class="anchored" data-anchor-id="why-golf-balls-are-this-size-and-why-they-have-dimples">Why Golf Balls Are This Size and Why They Have Dimples</h4>
<div class="golf-science-note">
<p>Modern golf balls are standardized for competitive fairness and flight consistency. Under the USGA/R&amp;A equipment rules, a conforming ball must not be smaller than 1.680 inches in diameter and must not be heavier than 1.620 ounces. That size-and-mass envelope keeps the ball large enough to see, strike, and control, while preventing an unfair aerodynamic advantage from a smaller or heavier ball.</p>
</div>
<p>The small dents on the ball are dimples, and they are there for aerodynamics rather than decoration. A smooth sphere at golf-ball speed creates a large turbulent wake behind it, which produces high pressure drag and makes the ball slow down quickly. Dimples intentionally disturb the thin boundary layer of air near the ball surface. That turbulent boundary layer stays attached farther around the back of the ball, shrinks the wake, and reduces pressure drag. With backspin, dimples also help the ball generate lift through the Magnus effect, which is why a well-struck driver shot can carry much farther than a smooth ball hit with the same speed.</p>
<p>Practical meaning for my practice: launch angle, spin rate, ball speed, and dimple-driven aerodynamics are tied together. Too much backspin can make the ball climb and lose distance; too little spin can reduce lift and make the ball fall early. For my driver, the goal is not just more ball speed, but a better launch/spin window.</p>
<p>Sources: <a href="https://www.usga.org/custom-search-pages/rules/equipment-rules/rule-14611.html">USGA Appendix III - The Ball</a>, <a href="https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/drag-of-a-sphere/">NASA Glenn on drag of a sphere</a>, and <a href="https://www.grc.nasa.gov/www/k-12/VirtualAero/BottleRocket/airplane/beach.html">NASA Glenn on spinning-ball aerodynamic force</a>.</p>
</section>
<section id="golftech-driver-best-shots---may-27-2026" class="level4">
<h4 class="anchored" data-anchor-id="golftech-driver-best-shots---may-27-2026">GolfTech Driver Best Shots - May 27, 2026</h4>
<p>These are my best two driver shots from last night’s GolfTech practice. The 207-yard shot was the longest total distance, while the 206-yard shot had the better carry and smash factor.</p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Shot</th>
<th style="text-align: right;">Total</th>
<th style="text-align: right;">Carry</th>
<th style="text-align: right;">Ball speed</th>
<th style="text-align: right;">Club speed</th>
<th style="text-align: right;">Launch</th>
<th style="text-align: right;">Backspin</th>
<th style="text-align: right;">Descent</th>
<th style="text-align: right;">Max height</th>
<th style="text-align: right;">Smash</th>
<th style="text-align: right;">Offline</th>
<th>Read</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">17 / 17</td>
<td style="text-align: right;">207 yd</td>
<td style="text-align: right;">187 yd</td>
<td style="text-align: right;">132 mph</td>
<td style="text-align: right;">89 mph</td>
<td style="text-align: right;">9 deg</td>
<td style="text-align: right;">3661 rpm</td>
<td style="text-align: right;">27 deg</td>
<td style="text-align: right;">14 yd</td>
<td style="text-align: right;">1.47</td>
<td style="text-align: right;">11 yd</td>
<td>Longest total distance; good speed, but launch was low and spin was high.</td>
</tr>
<tr class="even">
<td style="text-align: right;">10 / 10</td>
<td style="text-align: right;">206 yd</td>
<td style="text-align: right;">190 yd</td>
<td style="text-align: right;">127 mph</td>
<td style="text-align: right;">84 mph</td>
<td style="text-align: right;">16 deg</td>
<td style="text-align: right;">3167 rpm</td>
<td style="text-align: right;">40 deg</td>
<td style="text-align: right;">24 yd</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">40 yd</td>
<td>Best carry and smash factor; launch was in the target range, but dispersion needs work.</td>
</tr>
</tbody>
</table>
<div class="sports-metric-grid">
<div class="sports-metric-card">
<p><strong>Best total</strong></p>
<p>207 yd</p>
</div>
<div class="sports-metric-card">
<p><strong>Best carry</strong></p>
<p>190 yd</p>
</div>
<div class="sports-metric-card">
<p><strong>Best smash factor</strong></p>
<p>1.50</p>
</div>
<div class="sports-metric-card">
<p><strong>Top ball speed</strong></p>
<p>132 mph</p>
</div>
</div>
<div class="sports-image-grid">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/golftech-2026-05-27-driver-best-shot-207yd.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">GolfTech driver practice best total-distance shot: 207 yards total and 187 yards carry</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/golftech-2026-05-27-driver-best-shot-206yd.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">GolfTech driver practice best carry shot: 206 yards total and 190 yards carry</figcaption>
</figure>
</div>
</div>
</section>
<section id="current-golf-bag-fitting-setup" class="level4">
<h4 class="anchored" data-anchor-id="current-golf-bag-fitting-setup">Current Golf Bag Fitting Setup</h4>
<p>The table below records my current recommended bag setup from the club-fitting screenshots. The 7 iron and pitching wedge are treated as iron-set fitting anchors; I can expand this once the full iron set is finalized.</p>
<p><a href="data/golf_club_bag_fitting_2026-05-28.csv" class="btn btn-primary">Download current golf bag fitting CSV</a></p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Bag slot</th>
<th>Head</th>
<th>Loft / lie</th>
<th>Length</th>
<th>Shaft</th>
<th>Grip</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Driver</td>
<td>TaylorMade Qi35 Max</td>
<td>10.5 loft; adapter 0.75 up</td>
<td>45 in; standard 45.75 in</td>
<td>Fujikura Speeder NX TCS 50 R</td>
<td>Golf Pride MCC Plus 4, Gray/Blue, standard</td>
<td>Shorter-than-standard driver build for control.</td>
</tr>
<tr class="even">
<td>7 Iron</td>
<td>Callaway Elyte Max Fast</td>
<td>30 loft; 60.75 lie; 1.0 up</td>
<td>37.5 in</td>
<td>Mitsubishi Vanquish 40 R2</td>
<td>Golf Pride MCC Plus 4, Gray/Blue, standard</td>
<td>Iron fitting reference.</td>
</tr>
<tr class="odd">
<td>Pitching Wedge</td>
<td>Callaway Elyte Max Fast</td>
<td>43 loft; 60.75 lie; 1.0 up</td>
<td>35.75 in</td>
<td>Mitsubishi Vanquish 40 R2</td>
<td>Golf Pride MCC Plus 4, Gray/Blue, standard</td>
<td>Iron set wedge reference.</td>
</tr>
<tr class="even">
<td>56 Wedge</td>
<td>TaylorMade Milled Grind 5 Satin Chrome</td>
<td>56/10/SC; 64 lie</td>
<td>35.75 in; standard 35.25 in</td>
<td>Dynamic Gold Tour Issue 115 Wedge</td>
<td>Golf Pride MCC Plus 4, Gray/Blue, standard, +2 wraps</td>
<td>Slightly longer wedge with extra grip wraps.</td>
</tr>
<tr class="odd">
<td>Putter</td>
<td>Callaway Ai-ONE Silver Seven DB</td>
<td>3 loft; 70 lie</td>
<td>36 in</td>
<td>Odyssey SL 90 Putter Shaft</td>
<td>Callaway Ai-ONE Slim Pistol, white, putter size</td>
<td>Face-balanced style setup for putting stability.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="simulator-screenshot-gallery" class="level3">
<h3 class="anchored" data-anchor-id="simulator-screenshot-gallery">Simulator Screenshot Gallery</h3>
<div class="sports-image-grid">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/golf-2026-05-22-driver-list-shots-53-62.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Royal Golf Zone simulator driver list, shots 53 through 62</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/golf-2026-05-22-driver-list-shots-47-56.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Royal Golf Zone simulator driver list, shots 47 through 56</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/golf-2026-05-22-driver-list-shots-22-31.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Royal Golf Zone simulator driver list, shots 22 through 31</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/golf-2026-05-22-driver-list-shots-22-31-close.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Close-up Royal Golf Zone simulator driver list, shots 22 through 31</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/golf-2026-05-22-driver-analysis-shots-61-62.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Royal Golf Zone simulator shot analysis, shots 61 through 62</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/golf-2026-05-22-driver-analysis-shots-55-56.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Royal Golf Zone simulator shot analysis, shots 55 through 56</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/golf-2026-05-22-driver-analysis-shots-51-52.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Royal Golf Zone simulator shot analysis, shots 51 through 52</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/golf-2026-05-22-driver-analysis-shots-38-39.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Royal Golf Zone simulator shot analysis, shots 38 through 39</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/golf-2026-05-22-driver-analysis-shots-7-8.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Royal Golf Zone simulator shot analysis, shots 7 through 8</figcaption>
</figure>
</div>
</div>
</section>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<section id="road-bike-cycling-tracker" class="level3">
<h3 class="anchored" data-anchor-id="road-bike-cycling-tracker">Road Bike Cycling Tracker</h3>
<p>This section tracks my road bike training, Garmin ride summaries, White Rock Lake route practice, and future cycling-performance analytics. The current goal is to build a repeatable log for distance, speed, heart rate, cadence, climbing, temperature, and training notes.</p>
<div class="cycling-training-note">
<p><strong>Data note:</strong> the current Garmin CSV exports are lap/summary files, not full second-by-second GPS/FIT records. They are enough for ride-level analytics and lap comparison. For route replay, map traces, power curves, and time-series plots, I should also export <code>.fit</code>, <code>.gpx</code>, or <code>.tcx</code> files from Garmin Connect.</p>
</div>
</section>
<section id="bike-and-tracking-setup" class="level3">
<h3 class="anchored" data-anchor-id="bike-and-tracking-setup">Bike and Tracking Setup</h3>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>Current setup</th>
<th>What it supports</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Road bike</td>
<td>Trek <strong>Domane SL 5 Gen 4</strong></td>
<td>Endurance road bike built for long miles, rough roads, and comfort-focused training.</td>
</tr>
<tr class="even">
<td>Frame</td>
<td>500 Series OCLV Carbon</td>
<td>Lightweight endurance frame platform with comfort and stability as priorities.</td>
</tr>
<tr class="odd">
<td>Drivetrain</td>
<td>Shimano 105</td>
<td>Reliable road drivetrain for structured training and general performance riding.</td>
</tr>
<tr class="even">
<td>Wheels / cockpit</td>
<td>Aluminum wheels and aluminum handlebars</td>
<td>Balanced performance and value; good baseline before future upgrades.</td>
</tr>
<tr class="odd">
<td>GPS computer</td>
<td>Garmin <strong>Edge 840 Bundle</strong></td>
<td>Touchscreen + button cycling computer for navigation, ride planning, workout prompts, and performance tracking.</td>
</tr>
<tr class="even">
<td>Sensors</td>
<td>Speed Sensor 2, Cadence Sensor, HRM-Dual</td>
<td>Enables speed, cadence, and heart-rate tracking independent of only GPS estimates.</td>
</tr>
<tr class="odd">
<td>Current device status</td>
<td>Edge 840 software <code>30.18</code>; Speed Sensor 2 software <code>4.10</code>; sensor battery OK</td>
<td>Establishes a setup baseline for future ride logs.</td>
</tr>
<tr class="even">
<td>Future upgrade path</td>
<td>Compatible power meter</td>
<td>Would unlock Garmin power guide, stamina insights, cycling ability classification, and more complete adaptive coaching.</td>
</tr>
</tbody>
</table>
<p><a href="https://www.youtube.com/watch?v=6zvzwqUwtIw" class="btn btn-primary">Watch Trek Domane SL 5 Gen 4 intro video</a> <a href="data/cycling_ride_summary.csv" class="btn btn-secondary">Download cycling ride summary CSV</a> <a href="data/cycling_lap_summary.csv" class="btn btn-secondary">Download cycling lap summary CSV</a></p>
<p>Garmin Edge 840 capabilities I want to use as this tracker grows:</p>
<ul>
<li>Navigation and ride planning with touchscreen and button control.</li>
<li>Multi-band GNSS for better location accuracy in more challenging environments.</li>
<li>Daily suggested workouts, training prompts, and missed-workout reminders.</li>
<li>ClimbPro ascent planning to monitor remaining ascent and grade during climbs.</li>
<li>Ride-type maps that highlight popular roads, trails, and searchable points of interest.</li>
<li>Power guide, stamina insights, and cyclist ability/course-demand classification once I add a compatible power meter.</li>
</ul>
</section>
<section id="garmin-csv-summary" class="level3">
<h3 class="anchored" data-anchor-id="garmin-csv-summary">Garmin CSV Summary</h3>
<p>The current dataset contains six Garmin activity exports from the <code>cycling</code> folder. Because the CSV exports do not include ride dates, I use Garmin activity IDs and ride order as the tracking identifiers for now.</p>
<div class="sports-metric-grid">
<div class="sports-metric-card">
<p><strong>Logged rides</strong></p>
<p>6</p>
</div>
<div class="sports-metric-card">
<p><strong>Total distance</strong></p>
<p>54.76 mi</p>
</div>
<div class="sports-metric-card">
<p><strong>Total elapsed time</strong></p>
<p>4:00:02</p>
</div>
<div class="sports-metric-card">
<p><strong>Total moving time</strong></p>
<p>3:41:14</p>
</div>
<div class="sports-metric-card">
<p><strong>Moving avg speed</strong></p>
<p>14.85 mph</p>
</div>
<div class="sports-metric-card">
<p><strong>Avg heart rate</strong></p>
<p>125 bpm</p>
</div>
<div class="sports-metric-card">
<p><strong>Total ascent</strong></p>
<p>1,226 ft</p>
</div>
<div class="sports-metric-card">
<p><strong>Total calories</strong></p>
<p>2,168</p>
</div>
</div>
<div class="cycling-table-wrap">
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Ride</th>
<th style="text-align: right;">Garmin activity ID</th>
<th style="text-align: right;">Distance</th>
<th style="text-align: right;">Time</th>
<th style="text-align: right;">Moving time</th>
<th style="text-align: right;">Avg speed</th>
<th style="text-align: right;">Moving avg</th>
<th style="text-align: right;">Avg HR</th>
<th style="text-align: right;">Avg cadence</th>
<th style="text-align: right;">Ascent</th>
<th style="text-align: right;">Max speed</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">22109798266</td>
<td style="text-align: right;">9.12 mi</td>
<td style="text-align: right;">41:28</td>
<td style="text-align: right;">38:14</td>
<td style="text-align: right;">13.2 mph</td>
<td style="text-align: right;">14.3 mph</td>
<td style="text-align: right;">119 bpm</td>
<td style="text-align: right;">62 rpm</td>
<td style="text-align: right;">174 ft</td>
<td style="text-align: right;">21.6 mph</td>
<td>Dallas road cycling activity</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">22176079934</td>
<td style="text-align: right;">9.12 mi</td>
<td style="text-align: right;">44:54</td>
<td style="text-align: right;">35:59</td>
<td style="text-align: right;">12.2 mph</td>
<td style="text-align: right;">15.2 mph</td>
<td style="text-align: right;">113 bpm</td>
<td style="text-align: right;">66 rpm</td>
<td style="text-align: right;">190 ft</td>
<td style="text-align: right;">23.3 mph</td>
<td>Dallas road cycling activity</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">22301153174</td>
<td style="text-align: right;">10.03 mi</td>
<td style="text-align: right;">42:56</td>
<td style="text-align: right;">39:56</td>
<td style="text-align: right;">14.0 mph</td>
<td style="text-align: right;">15.1 mph</td>
<td style="text-align: right;">131 bpm</td>
<td style="text-align: right;">61 rpm</td>
<td style="text-align: right;">236 ft</td>
<td style="text-align: right;">23.8 mph</td>
<td>Longest current logged ride</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">22311683203</td>
<td style="text-align: right;">9.18 mi</td>
<td style="text-align: right;">38:30</td>
<td style="text-align: right;">37:24</td>
<td style="text-align: right;">14.3 mph</td>
<td style="text-align: right;">14.7 mph</td>
<td style="text-align: right;">131 bpm</td>
<td style="text-align: right;">62 rpm</td>
<td style="text-align: right;">226 ft</td>
<td style="text-align: right;">24.4 mph</td>
<td>Fastest max speed</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">22366655913</td>
<td style="text-align: right;">9.25 mi</td>
<td style="text-align: right;">39:29</td>
<td style="text-align: right;">38:01</td>
<td style="text-align: right;">14.1 mph</td>
<td style="text-align: right;">14.6 mph</td>
<td style="text-align: right;">131 bpm</td>
<td style="text-align: right;">61 rpm</td>
<td style="text-align: right;">259 ft</td>
<td style="text-align: right;">23.5 mph</td>
<td>White Rock Lake ride from screenshot</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">23073973446</td>
<td style="text-align: right;">8.06 mi</td>
<td style="text-align: right;">32:45</td>
<td style="text-align: right;">31:40</td>
<td style="text-align: right;">14.8 mph</td>
<td style="text-align: right;">15.3 mph</td>
<td style="text-align: right;">128 bpm</td>
<td style="text-align: right;">66 rpm</td>
<td style="text-align: right;">141 ft</td>
<td style="text-align: right;">23.4 mph</td>
<td>Best current average speed</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="white-rock-lake-baseline-ride" class="level3">
<h3 class="anchored" data-anchor-id="white-rock-lake-baseline-ride">White Rock Lake Baseline Ride</h3>
<p>The White Rock Lake ride shown in the Garmin screenshot is activity <code>22366655913</code>: 9.25 miles in 39:29, with 14.1 mph average speed, 14.6 mph moving average speed, 131 bpm average heart rate, 61 rpm average cadence, and 259 ft total ascent.</p>
<div class="cycling-visual-grid">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/cycling-white-rock-lake-route.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Garmin Connect White Rock Lake road cycling route plot</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/cycling-garmin-edge-840-sensor-status.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Garmin Edge 840 and Speed Sensor 2 setup status</figcaption>
</figure>
</div>
</div>
</section>
<section id="cycling-analytics" class="level3">
<h3 class="anchored" data-anchor-id="cycling-analytics">Cycling Analytics</h3>
<div class="cycling-visual-grid">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/cycling-performance-trends.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Cycling performance trend from Garmin CSV exports</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/cycling-ride-distance-baseline.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Cycling ride distance baseline chart</figcaption>
</figure>
</div>
</div>
<p>Early read from the Garmin data:</p>
<ul>
<li>Across six logged rides, the current training baseline is about 55 miles total, with a weighted moving average speed of 14.85 mph.</li>
<li>Moving speed is more stable than elapsed speed. This means stops, traffic, intersections, or route interruptions are affecting elapsed pace more than riding pace.</li>
<li>The strongest current average-speed ride is activity <code>23073973446</code> at 14.8 mph elapsed average and 15.3 mph moving average.</li>
<li>The longest current ride is activity <code>22301153174</code> at 10.03 miles.</li>
<li>The highest-climbing current ride is the White Rock Lake activity <code>22366655913</code> with 259 ft of ascent.</li>
<li>Average cadence is currently around 63 rpm. A useful future focus is tracking whether smoother cadence work, bike fit, and route choice can gradually raise comfortable cadence while keeping heart rate controlled.</li>
<li>Heart rate rose from the first two rides into the 128-131 bpm range on later rides, while speed also improved. That suggests later rides were more sustained training efforts rather than only casual cruising.</li>
</ul>
</section>
<section id="future-cycling-data-fields" class="level3">
<h3 class="anchored" data-anchor-id="future-cycling-data-fields">Future Cycling Data Fields</h3>
<p>For each future ride, I should record:</p>
<ul>
<li>Date, start time, route name, weather, temperature, wind, and traffic/stop context.</li>
<li>Bike used, tire pressure, sensor status, and whether the HRM-Dual was connected.</li>
<li>Distance, elapsed time, moving time, average speed, moving average speed, max speed.</li>
<li>Average heart rate, max heart rate, average cadence, max cadence, calories, ascent, and descent.</li>
<li>Optional future power metrics: average power, normalized power, power zones, training stress, stamina, and power-guide targets.</li>
<li>Subjective notes: perceived effort, comfort, fueling, hydration, saddle/fit issues, and one next-ride focus.</li>
</ul>
</section>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<section id="pool-swim-tracker" class="level3">
<h3 class="anchored" data-anchor-id="pool-swim-tracker">Pool Swim Tracker</h3>
<p>This section tracks my pool swimming practice, Apple Watch workout summaries, stroke mix, heart-rate response, SWOLF/efficiency signals, and future swim-training progress. The first logged session was at the <a href="https://www.smu.edu/studentaffairs/campus-recreation/facilities/pool">SMU Campus Recreation pool</a>. SMU describes the Dedman Center indoor pool as a 5-lane, 25-yard pool, which matches the <code>25 yd</code> pool length recorded by my Apple Watch.</p>
<div class="swimming-training-note">
<p><strong>Data note:</strong> this first swim log is transcribed from Apple Watch screenshots, not from a raw Apple Health export. The screenshots are useful for workout summary, auto sets, heart-rate zones, and stroke totals. For deeper analysis later, I should export Apple Health workout data so I can analyze lap-by-lap timing, heart-rate samples, and pace trends more precisely.</p>
</div>
</section>
<section id="june-1-2026-smu-pool-swim" class="level3">
<h3 class="anchored" data-anchor-id="june-1-2026-smu-pool-swim">June 1, 2026 SMU Pool Swim</h3>
<p><a href="data/swimming_workout_log.csv" class="btn btn-primary">Download swim workout CSV</a> <a href="data/swimming_auto_sets_2026-06-01.csv" class="btn btn-secondary">Download auto sets CSV</a> <a href="data/swimming_stroke_breakdown_2026-06-01.csv" class="btn btn-secondary">Download stroke breakdown CSV</a></p>
<div class="sports-metric-grid">
<div class="sports-metric-card">
<p><strong>Distance</strong></p>
<p>550 yd</p>
</div>
<div class="sports-metric-card">
<p><strong>Laps</strong></p>
<p>22</p>
</div>
<div class="sports-metric-card">
<p><strong>Pool length</strong></p>
<p>25 yd</p>
</div>
<div class="sports-metric-card">
<p><strong>Workout time</strong></p>
<p>51:41</p>
</div>
<div class="sports-metric-card">
<p><strong>Avg pace</strong></p>
<p>9:36 /100 yd</p>
</div>
<div class="sports-metric-card">
<p><strong>Avg HR</strong></p>
<p>106 bpm</p>
</div>
<div class="sports-metric-card">
<p><strong>Active calories</strong></p>
<p>186</p>
</div>
<div class="sports-metric-card">
<p><strong>Effort</strong></p>
<p>6 Moderate</p>
</div>
</div>
<table class="table">
<thead>
<tr class="header">
<th>Field</th>
<th>Session record</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Date</td>
<td>2026-06-01</td>
</tr>
<tr class="even">
<td>Time</td>
<td>5:46 PM to 6:38 PM</td>
</tr>
<tr class="odd">
<td>Location</td>
<td>University Park, Texas</td>
</tr>
<tr class="even">
<td>Venue</td>
<td><a href="https://www.smu.edu/studentaffairs/campus-recreation/facilities/pool">SMU Campus Recreation Pool</a></td>
</tr>
<tr class="odd">
<td>Workout type</td>
<td>Pool Swim</td>
</tr>
<tr class="even">
<td>Distance</td>
<td>550 yd</td>
</tr>
<tr class="odd">
<td>Pool length</td>
<td>25 yd</td>
</tr>
<tr class="even">
<td>Laps</td>
<td>22</td>
</tr>
<tr class="odd">
<td>Workout time</td>
<td>0:51:41</td>
</tr>
<tr class="even">
<td>Average pace</td>
<td>9:36 / 100 yd</td>
</tr>
<tr class="odd">
<td>Average heart rate</td>
<td>106 bpm</td>
</tr>
<tr class="even">
<td>Active / total calories</td>
<td>186 / 270 cal</td>
</tr>
<tr class="odd">
<td>Effort</td>
<td>6 - Moderate</td>
</tr>
</tbody>
</table>
</section>
<section id="stroke-mix" class="level3">
<h3 class="anchored" data-anchor-id="stroke-mix">Stroke Mix</h3>
<p>The Apple Watch stroke summary shows that this session was mainly breaststroke, with smaller amounts of freestyle, kickboard work, backstroke, and mixed stroke work.</p>
<div class="swimming-visual-grid">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/swimming-2026-06-01-stroke-breakdown.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Stroke distance breakdown for the June 1, 2026 pool swim</figcaption>
</figure>
</div>
</div>
<table class="table">
<thead>
<tr class="header">
<th>Stroke</th>
<th style="text-align: right;">Distance</th>
<th style="text-align: right;">Laps</th>
<th style="text-align: right;">Share of distance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Breaststroke</td>
<td style="text-align: right;">350 yd</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">63.6%</td>
</tr>
<tr class="even">
<td>Freestyle</td>
<td style="text-align: right;">100 yd</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">18.2%</td>
</tr>
<tr class="odd">
<td>Kickboard</td>
<td style="text-align: right;">50 yd</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">9.1%</td>
</tr>
<tr class="even">
<td>Backstroke</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.5%</td>
</tr>
<tr class="odd">
<td>Mixed</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.5%</td>
</tr>
</tbody>
</table>
</section>
<section id="heart-rate-and-intensity-read" class="level3">
<h3 class="anchored" data-anchor-id="heart-rate-and-intensity-read">Heart-Rate and Intensity Read</h3>
<table class="table">
<thead>
<tr class="header">
<th>Heart-rate zone</th>
<th style="text-align: right;">Time</th>
<th>Range</th>
<th>Training read</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zone 1</td>
<td style="text-align: right;">48:58</td>
<td>&lt;133 bpm</td>
<td>Easy aerobic / technique work</td>
</tr>
<tr class="even">
<td>Zone 2</td>
<td style="text-align: right;">0:37</td>
<td>134-146 bpm</td>
<td>Brief moderate effort</td>
</tr>
<tr class="odd">
<td>Zone 3</td>
<td style="text-align: right;">0:00</td>
<td>147-160 bpm</td>
<td>None</td>
</tr>
<tr class="even">
<td>Zone 4</td>
<td style="text-align: right;">0:00</td>
<td>161-173 bpm</td>
<td>None</td>
</tr>
<tr class="odd">
<td>Zone 5</td>
<td style="text-align: right;">0:00</td>
<td>174+ bpm</td>
<td>None</td>
</tr>
</tbody>
</table>
<p>Early read:</p>
<ul>
<li>This was mostly a low-intensity aerobic and technique session: average heart rate was 106 bpm, and almost all recorded zone time was in Zone 1.</li>
<li>The session distance was 550 yd, which matches 22 lengths in a 25 yd pool.</li>
<li>Breaststroke was the dominant stroke at 350 yd, or 63.6% of total distance.</li>
<li>The post-workout heart-rate values declined from 108 bpm at finish to 105 bpm at 1 minute and 102 bpm at 2 minutes. Because the workout was mostly Zone 1, a small recovery drop is not surprising.</li>
<li>The first auto set appears unusually long for a 25 yd freestyle length, and set 12 appears unusually fast for a 25 yd breaststroke length. I should treat those as possible Apple Watch auto-set detection artifacts until more swim sessions confirm the pattern.</li>
</ul>
</section>
<section id="auto-sets" class="level3">
<h3 class="anchored" data-anchor-id="auto-sets">Auto Sets</h3>
<p>The table below records the visible Apple Watch auto-set data. SWOLF is a rough efficiency indicator combining swim time and stroke count for a pool length, so lower can be better when distance and stroke type are comparable. It should not be compared too aggressively across different strokes or across sets with possible detection artifacts.</p>
<div class="swimming-table-wrap">
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Set</th>
<th>Stroke</th>
<th style="text-align: right;">Distance</th>
<th style="text-align: right;">Swim</th>
<th style="text-align: right;">Rest</th>
<th style="text-align: right;">Visible stroke count</th>
<th style="text-align: right;">Avg SWOLF</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td>Freestyle</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">10:47</td>
<td style="text-align: right;">0:58</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">46</td>
<td>Warm-up or Apple auto-set artifact</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td>Freestyle</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">0:33</td>
<td style="text-align: right;">4:24</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">48</td>
<td></td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td>Breaststroke</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">0:45</td>
<td style="text-align: right;">0:21</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">60</td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td>Breaststroke</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">0:42</td>
<td style="text-align: right;">1:07</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">55</td>
<td></td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td>Backstroke</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">0:39</td>
<td style="text-align: right;">1:45</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">51</td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td>Breaststroke</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">0:37</td>
<td style="text-align: right;">1:03</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">48</td>
<td></td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td>Breaststroke</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">0:39</td>
<td style="text-align: right;">0:52</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">50</td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td>Mixed</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">0:34</td>
<td style="text-align: right;">2:23</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;"></td>
<td></td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td>Kickboard</td>
<td style="text-align: right;">50 yd</td>
<td style="text-align: right;">0:50</td>
<td style="text-align: right;">0:32</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"></td>
<td>Kickboard set</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td>Freestyle</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">0:33</td>
<td style="text-align: right;">0:47</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">44</td>
<td></td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td>Breaststroke</td>
<td style="text-align: right;">75 yd</td>
<td style="text-align: right;">3:38</td>
<td style="text-align: right;">1:39</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">86</td>
<td>Long breaststroke set</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td>Breaststroke</td>
<td style="text-align: right;">25 yd</td>
<td style="text-align: right;">0:19</td>
<td style="text-align: right;">2:53</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">26</td>
<td>Very fast detected set; verify later</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td>Breaststroke</td>
<td style="text-align: right;">50 yd</td>
<td style="text-align: right;">1:48</td>
<td style="text-align: right;">1:09</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">66</td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td>Breaststroke</td>
<td style="text-align: right;">50 yd</td>
<td style="text-align: right;">1:29</td>
<td style="text-align: right;">1:07</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">58</td>
<td></td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td>Breaststroke</td>
<td style="text-align: right;">75 yd</td>
<td style="text-align: right;">1:43</td>
<td style="text-align: right;">0:00</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">45</td>
<td>Strong closing breaststroke set</td>
</tr>
</tbody>
</table>
</div>
<div class="swimming-visual-grid">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/swimming-2026-06-01-auto-sets-1-7.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Apple Watch auto sets 1 through 7 for the June 1, 2026 swim</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/swimming-2026-06-01-auto-sets-7-13.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Apple Watch auto sets 7 through 13 for the June 1, 2026 swim</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/swimming-2026-06-01-auto-sets-10-15.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Apple Watch auto sets 10 through 15 for the June 1, 2026 swim</figcaption>
</figure>
</div>
</div>
</section>
<section id="future-swimming-data-fields" class="level3">
<h3 class="anchored" data-anchor-id="future-swimming-data-fields">Future Swimming Data Fields</h3>
<p>For each future swim, I should record:</p>
<ul>
<li>Date, pool, pool length, workout duration, distance, laps, stroke mix, and perceived effort.</li>
<li>Average pace, best set pace, active calories, total calories, average heart rate, max heart rate, and heart-rate zone time.</li>
<li>Auto-set table with stroke, distance, swim time, rest time, stroke count, and SWOLF.</li>
<li>Notes about technique: breathing, kick rhythm, body position, turn quality, fatigue, and shoulder comfort.</li>
<li>A specific next-session goal, such as reaching 750 yd total, reducing long rests, improving freestyle volume, or keeping breaststroke SWOLF more stable.</li>
</ul>
</section>
</div>
<div id="tabset-2-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-5-tab">
<p>This section tracks my Private Pilot License training flights, ForeFlight debriefs, route history, and flight-performance patterns over time. The goal is to make each lesson reviewable: where I flew, how the altitude and speed profile looked, what ForeFlight scored well, and what I should focus on in the next flight.</p>
<div class="flight-training-note">
<p><strong>Training review only:</strong> these plots and logs are for personal learning and post-flight analysis. They are not for navigation, dispatch, or operational flight planning.</p>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Flight Log</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Track Visuals</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Training Read</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">Journal System</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<section id="foreflight-track-log-ksep-to-kftw" class="level4">
<h4 class="anchored" data-anchor-id="foreflight-track-log-ksep-to-kftw">ForeFlight Track Log: KSEP to KFTW</h4>
<p>This entry uses the downloaded ForeFlight CSV/KML track log and the ForeFlight navlog PDF from my February 22, 2026 training flight.</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Record</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Date</td>
<td>February 22, 2026</td>
</tr>
<tr class="even">
<td>Route</td>
<td>KSEP -&gt; KFTW</td>
</tr>
<tr class="odd">
<td>Aircraft</td>
<td>N2236W, P28A - PA-28-161 Warrior II</td>
</tr>
<tr class="even">
<td>Track window</td>
<td>4:46:52 PM to about 6:20 PM CST</td>
</tr>
<tr class="odd">
<td>ForeFlight debrief score</td>
<td>98 overall, 100 maneuvers, 97 approaches</td>
</tr>
<tr class="even">
<td>Planned navlog distance</td>
<td>73 NM</td>
</tr>
<tr class="odd">
<td>Actual track distance</td>
<td>84.8 NM</td>
</tr>
<tr class="even">
<td>Track duration</td>
<td>1:33:30</td>
</tr>
<tr class="odd">
<td>Planned cruise altitude</td>
<td>3,500 ft</td>
</tr>
<tr class="even">
<td>Maximum recorded altitude</td>
<td>3,495 ft MSL</td>
</tr>
<tr class="odd">
<td>Maximum ground speed</td>
<td>116.5 kt</td>
</tr>
<tr class="even">
<td>Moving average ground speed</td>
<td>95.4 kt, using samples with ground speed at least 30 kt</td>
</tr>
</tbody>
</table>
<p><a href="data/flight_training_log.csv" class="btn btn-primary">Download flight journal CSV</a> <a href="data/flight_2026-02-22_track_samples_15s.csv" class="btn btn-secondary">Download sampled track CSV</a> <a href="files/sports/flight/foreflight-2026-02-22-tracklog.csv" class="btn btn-secondary">Download raw ForeFlight CSV</a> <a href="files/sports/flight/foreflight-2026-02-22-tracklog.kml" class="btn btn-secondary">Download raw KML</a> <a href="files/sports/flight/foreflight-2026-02-22-navlog.pdf" class="btn btn-secondary">View ForeFlight navlog PDF</a> <a href="https://plan.foreflight.com/shared/debrief/track/b00b9008-962e-415f-b88c-1b375792dd6d" class="btn btn-secondary">Open shared ForeFlight debrief</a></p>
<div class="sports-metric-grid">
<div class="sports-metric-card">
<p><strong>Overall score</strong></p>
<p>98</p>
</div>
<div class="sports-metric-card">
<p><strong>Track distance</strong></p>
<p>84.8 NM</p>
</div>
<div class="sports-metric-card">
<p><strong>Duration</strong></p>
<p>1:33:30</p>
</div>
<div class="sports-metric-card">
<p><strong>Max altitude</strong></p>
<p>3,495 ft</p>
</div>
<div class="sports-metric-card">
<p><strong>Max GS</strong></p>
<p>116.5 kt</p>
</div>
<div class="sports-metric-card">
<p><strong>Moving avg GS</strong></p>
<p>95.4 kt</p>
</div>
</div>
</section>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="flight-visual-grid">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/flight-2026-02-22-route-map.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">ForeFlight-derived route map from KSEP to KFTW</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/flight-2026-02-22-altitude-groundspeed-profile.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Altitude and ground-speed profile from the ForeFlight CSV track log</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sports/flight-2026-02-22-navlog-page1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">ForeFlight navlog preview for the KSEP to KFTW training flight</figcaption>
</figure>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>The first data read from this flight is encouraging:</p>
<ul>
<li>ForeFlight scored the lesson strongly: 98 overall, with 100 for maneuvers and 97 for approaches.</li>
<li>The planned navlog route was 73 NM, while the downloaded track totals 84.8 NM. That difference is expected because the track log includes the full recorded path and any extra maneuvering, holding, taxi, or setup portions.</li>
<li>The main cruise profile stayed close to the planned 3,500 ft target, with a maximum recorded altitude of 3,495 ft MSL.</li>
<li>Moving samples averaged 95.4 kt ground speed, and the maximum recorded ground speed was 116.5 kt.</li>
<li>The altitude/ground-speed profile is the most useful training plot because it shows level-off quality, cruise steadiness, descent timing, and approach-energy management in one view.</li>
</ul>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<p>For future PPL training flights, this page should track both the official logbook facts and the learning notes:</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>Fields to record</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Flight identity</td>
<td>Date, aircraft tail, aircraft type, route, origin, destination, instructor, lesson number</td>
</tr>
<tr class="even">
<td>Logbook data</td>
<td>Total time, dual received, PIC if applicable, landings, day/night, cross-country, simulated instrument</td>
</tr>
<tr class="odd">
<td>ForeFlight debrief</td>
<td>Overall score, maneuvers score, approaches score, route image, altitude profile, ground-speed profile</td>
</tr>
<tr class="even">
<td>Training content</td>
<td>Maneuvers practiced, pattern work, radio work, navigation tasks, checklist discipline</td>
</tr>
<tr class="odd">
<td>Reflection</td>
<td>What improved, what felt unstable, what to ask the instructor, next-flight focus</td>
</tr>
<tr class="even">
<td>Data files</td>
<td>ForeFlight CSV, KML, navlog PDF, screenshots, notes, weather context</td>
</tr>
</tbody>
</table>
<p>As more flights are added, I can turn this into a real flight-training dashboard with monthly hours, airports visited, landing counts, maneuver history, route maps, and milestone progress toward the Private Pilot License.</p>
</div>
</div>
</div>
</div>
</div>
</div>



</main> <!-- /main -->
<script src="language-switcher.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© 2026 Li Yuan (Leon) | PhD Candidate in Statistical Science, Southern Methodist University</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>